<?php

namespace Spawnflow\Generator;

use Illuminate\Support\Str;

/**
 * Emits TypeScript artifacts from contract schemas (SchemaSerializer
 * output): a field-map type, field metadata, per-variant Zod schemas, a
 * context-keyed schema map, and optionally a discriminated variant union.
 *
 * The generator consumes the CONTRACT, not package internals — anything
 * the live schema endpoint serves, these files agree with.
 */
class TypeScriptGenerator
{
    public function __construct(protected array $config = []) {}

    /**
     * One .ts module per subject.
     *
     * @param  array  $schema  A variants or default contract schema.
     */
    public function subjectFile(array $schema): string
    {
        $alias = $schema['resource'];
        $prefix = Str::studly($alias);
        $fields = $schema['fields'];
        $variants = $this->normalizeVariants($schema);

        $out = "// Generated by Spawnflow (contract v{$schema['spawnflow']}) — do not edit.\n";
        $out .= "import { z } from 'zod';\n\n";

        // Field-map type from descriptors.
        $out .= "export type {$prefix}Fields = {\n";
        foreach ($fields as $name => $descriptor) {
            $out .= "  {$name}: {$this->tsType($descriptor)};\n";
        }
        $out .= "};\n\n";

        // Field metadata (widgets, labels, options, relations) for renderers.
        $meta = json_encode($fields, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        $out .= "export const {$this->camel($alias)}FieldMeta = {$meta} as const;\n\n";

        // Per-variant Zod schemas.
        $schemaNames = [];
        foreach ($variants as $variant) {
            $schemaName = $this->camel($alias).Str::studly($this->identifier($variant['context'])).'Schema';
            $schemaNames[$variant['context']] = $schemaName;

            $out .= "export const {$schemaName} = z.object({\n";
            foreach ($variant['editable_fields'] as $name) {
                $expr = ZodCompiler::compile($fields[$name] ?? ['type' => 'string'], $variant['rules'][$name] ?? []);
                $out .= "  {$name}: {$expr},\n";
            }
            $out .= "});\n\n";
        }

        // Context-keyed maps.
        $out .= "export const {$this->camel($alias)}Schemas = {\n";
        foreach ($schemaNames as $context => $schemaName) {
            $out .= "  '{$context}': {$schemaName},\n";
        }
        $out .= "} as const;\n\n";

        $out .= "export type {$prefix}Context = keyof typeof {$this->camel($alias)}Schemas;\n\n";

        $out .= "export const {$this->camel($alias)}Variants = {\n";
        foreach ($variants as $variant) {
            $editable = $this->stringArray($variant['editable_fields']);
            $visible = $this->stringArray($variant['visible_fields']);
            $out .= "  '{$variant['context']}': { editable: {$editable}, visible: {$visible} },\n";
        }
        $out .= "} as const;\n";

        // Discriminated union over variants.
        if ($this->config['emit_unions'] ?? true) {
            $out .= "\nexport type {$prefix}Variant =\n";
            $arms = [];
            foreach ($variants as $variant) {
                $editable = $variant['editable_fields'] === []
                    ? 'Record<string, never>'
                    : "Pick<{$prefix}Fields, ".implode(' | ', array_map(fn ($f) => "'{$f}'", $variant['editable_fields'])).'>';
                $arms[] = "  | { context: '{$variant['context']}'; editable: {$editable} }";
            }
            $out .= implode("\n", $arms).";\n";
        }

        return $out;
    }

    /**
     * @param  list<string>  $aliases
     */
    public function indexFile(array $aliases): string
    {
        $out = "// Generated by Spawnflow — do not edit.\n";
        foreach ($aliases as $alias) {
            $out .= "export * from './{$alias}';\n";
        }

        if ($this->config['emit_client'] ?? false) {
            $out .= "export * from './client';\n";
        }

        return $out;
    }

    /**
     * Thin fetch client for SpawnflowController + schema routes.
     */
    public function clientFile(): string
    {
        return <<<'TS'
// Generated by Spawnflow — do not edit.

export interface SpawnflowClientOptions {
  baseUrl?: string;
  headers?: Record<string, string> | (() => Record<string, string>);
  fetch?: typeof fetch;
}

export function createSpawnflowClient(options: SpawnflowClientOptions = {}) {
  const baseUrl = (options.baseUrl ?? '').replace(/\/$/, '');
  const doFetch = options.fetch ?? fetch;

  async function request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const headers = typeof options.headers === 'function' ? options.headers() : (options.headers ?? {});
    const response = await doFetch(`${baseUrl}${path}`, {
      method,
      headers: { Accept: 'application/json', 'Content-Type': 'application/json', ...headers },
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    if (!response.ok) {
      throw Object.assign(new Error(`Spawnflow request failed: ${response.status}`), {
        status: response.status,
        response,
      });
    }
    return response.status === 204 ? (undefined as T) : ((await response.json()) as T);
  }

  return {
    list: <T>(subject: string, params: Record<string, string | number> = {}) => {
      const query = new URLSearchParams(Object.entries(params).map(([k, v]) => [k, String(v)]));
      const qs = query.size ? `?${query}` : '';
      return request<T>('GET', `/${subject}${qs}`);
    },
    create: <T>(subject: string, data: unknown) => request<T>('POST', `/${subject}`, data),
    update: <T>(subject: string, id: number, data: unknown) => request<T>('POST', `/${subject}/${id}`, data),
    destroy: (subject: string, id: number) => request<void>('DELETE', `/${subject}/${id}`),
    schema: <T>(subject: string, id?: number) =>
      request<T>('GET', `/spawnflow/schema/${subject}${id === undefined ? '' : `/${id}`}`),
  };
}
TS;
    }

    // ---------------------------------------------------------------
    // Internals
    // ---------------------------------------------------------------

    /**
     * A default (context-less) schema becomes a single 'default' variant so
     * downstream emission has one shape to handle.
     *
     * @return list<array{context: string, editable_fields: list<string>, visible_fields: list<string>, rules: array}>
     */
    protected function normalizeVariants(array $schema): array
    {
        if (isset($schema['variants'])) {
            return $schema['variants'];
        }

        $rules = [];
        foreach ($schema['fields'] as $name => $descriptor) {
            $rules[$name] = $descriptor['rules'] ?? [];
        }

        return [[
            'context' => $schema['context'] ?? 'default',
            'editable_fields' => array_keys($schema['fields']),
            'visible_fields' => array_keys($schema['fields']),
            'rules' => $rules,
        ]];
    }

    protected function tsType(array $descriptor): string
    {
        $type = match ($descriptor['type'] ?? 'string') {
            'int', 'float' => 'number',
            'bool' => 'boolean',
            'enum' => $this->enumTsType($descriptor['options'] ?? []),
            'relation' => ($descriptor['relation']['multiple'] ?? false) ? 'number[]' : 'number',
            'json' => 'unknown',
            'file' => 'File',
            default => 'string',
        };

        return ($descriptor['nullable'] ?? false) ? "{$type} | null" : $type;
    }

    /**
     * @param  list<array{value: mixed}>  $options
     */
    protected function enumTsType(array $options): string
    {
        if ($options === []) {
            return 'never';
        }

        return implode(' | ', array_map(
            fn (array $option) => is_string($option['value']) ? "'{$option['value']}'" : (string) $option['value'],
            $options,
        ));
    }

    /**
     * @param  list<string>  $values
     */
    protected function stringArray(array $values): string
    {
        return '['.implode(', ', array_map(fn (string $value) => "'{$value}'", $values)).']';
    }

    protected function camel(string $value): string
    {
        return Str::camel($this->identifier($value));
    }

    /**
     * Contexts like 'owner:draft' become identifier-safe ('owner draft').
     */
    protected function identifier(string $value): string
    {
        return trim(preg_replace('/[^a-zA-Z0-9]+/', ' ', $value));
    }
}
